DATA_DIR = "../data/"
CSV_PATH = "../data/"
CHECKPOINT_PATH = "../checkpoint"
PLOT_PATH = "../plots"
# DATA_DIR = "/content/drive/MyDrive/data/melanoma"
# CHECKPOINT_PATH = "/content/drive/MyDrive/data/melanoma/checkpoint"
# PLOT_PATH = "/content/drive/MyDrive/data/melanoma/plots"
TRAIN_BATCH_SIZE = 32
EVAL_BATCH_SIZE = 16
IMAGE_WIDTH = 300
IMAGE_HEIGHT = 75
NUM_WORKERS = 0
DEVICE = "cpu"
EPOCHS = 2